# Generated by Django 5.2.3 on 2025-06-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='segment',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Mainstream', 'Mainstream'), ('Affordable', 'Affordable')], default='Mainstream', max_length=20),
        ),
    ]
