# Generated by Django 5.2.3 on 2025-06-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_remove_brand_country'),
        ('products', '0003_remove_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('brand', 'sku')},
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
