# Generated by Django 5.2.3 on 2025-06-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_delete_category_alter_product_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="segment",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("Lager", "Lager"),
                    ("Stout", "Stout"),
                    ("Malt", "Malt"),
                    ("Rtd", "Rtd"),
                ],
                default="Lager",
                max_length=20,
            ),
        ),
    ]
