# Generated by Django 5.2.3 on 2025-06-29 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_product_segment_product_image_and_more"),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock",
                to="products.product",
            ),
        ),
    ]
